spring:
  datasource:
    url: jdbc:mysql://localhost:3306/przepisy
    username: root
    password: Sumek2490!!
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:///C:/uploads/
app:
  storage:
    location: ./uploads/
